version: '3'

services:
  dotnetmicroservices.spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  dotnetmicroservices.idp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  dotnetmicroservices.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  dotnetmicroservices.db:
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=123456

  dotnetmicroservices.dbinitializer:
    environment:
      - DatabaseConnection=Server=dotnetmicroservices.db;Database=InteractiveStories;Username=pgadmin;Password=123456