version: '3'

services:
  dotnetmicroservices.spa:
    image: cleverices/dotnetmicroservices.spa
    build:
      context: ./DotNetMicroservices.SPA
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  dotnetmicroservices.idp:
    image: cleverices/dotnetmicroservices.idp
    build:
      context: ./DotNetMicroservices.IDP
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - dotnetmicroservices.db

  dotnetmicroservices.api:
    image: cleverices/dotnetmicroservices.api
    build:
      context: ./DotNetMicroservices.API
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - dotnetmicroservices.db

  dotnetmicroservices.db:
    image: postgres
    ports:
      - "5432:5432"

  dotnetmicroservices.dbinitializer:
    image: cleverices/dotnetmicroservices.dbinitializer
    build:
      context: ./DotNetMicroservices.DB
      dockerfile: Dockerfile
    depends_on:
      - dotnetmicroservices.db
