version: '3'

services:
  spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  idp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=123456